module.exports = {
   cookies: [
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012562,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-1PAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: '_vg-Kw7af5LTBJq0/A7jsRVrzAZ2r9KIea',
         id: 1,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012675,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000mQgFegrpHiQI5ErTzgDMnU-BwcjKhaxRNqZEMCerMga7uTFIwGiVV8dnisXDx9kKZS0o3QACgYKAYASARMSFQHGX2Mis0DGWeGLYFT9TJDpn7nC1hoVAUF8yKqw_WIV2TehmSDmBKqxkipE0076',
         id: 2,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754567223.567873,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzXxdidhrtwBUvaA0jh_yswYB3pUQ7p-vYhosOr4itwVPHPW8tVcM5Vg3eNnL3YhMhixsw',
         id: 3,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754567222.091716,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-1PSIDTS',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjEB4E2dkcZacszaN81h5trr9CmufwYzuFRnPvltxFYvVxUsw03lNokRLpWSC-bNWufdEAA',
         id: 4,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012584,
         hostOnly: false,
         httpOnly: false,
         name: '__Secure-3PAPISID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: '_vg-Kw7af5LTBJq0/A7jsRVrzAZ2r9KIea',
         id: 5,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012693,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSID',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'g.a000mQgFegrpHiQI5ErTzgDMnU-BwcjKhaxRNqZEMCerMga7uTFILlBm9sxRi7kQNOXT_vaVqAACgYKAdESARMSFQHGX2MiDlG6c_PZL-pgefZFF9tqYRoVAUF8yKon_Lq8TSi7wFVibKdTwemE0076',
         id: 6,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754567223.567916,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDCC',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AKEyXzWgBc8tbUtLNHba7PJhYGKO9UYo7-nyMeGXKf_pUWWIh7HkHFm1T30UedOvMgdirfeU',
         id: 7,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754567222.091802,
         hostOnly: false,
         httpOnly: true,
         name: '__Secure-3PSIDTS',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'sidts-CjEB4E2dkcZacszaN81h5trr9CmufwYzuFRnPvltxFYvVxUsw03lNokRLpWSC-bNWufdEAA',
         id: 8,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012517,
         hostOnly: false,
         httpOnly: false,
         name: 'APISID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'GPtH9hFPb8ATTcJP/AjW5xaxrXytCyZ3Ui',
         id: 9,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012425,
         hostOnly: false,
         httpOnly: true,
         name: 'HSID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AmqMKFQohf7RV8ghR',
         id: 10,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754377166.259281,
         hostOnly: false,
         httpOnly: true,
         name: 'LOGIN_INFO',
         path: '/',
         sameSite: 'no_restriction',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AFmmF2swRQIhAJJCEiUFD50BzWt0jLTakv4Jg0jVFNOheBbjgxeLT71IAiBqdYPWB8blSoq5R_yZj3R0P3arQUbO1UHtCpRmEkuJtw:QUQ3MjNmekd5UFU4VzQ2ejV4Wi1JRDE4Z0VoSVB5Mm52WGhaVmJFeDhfYllHS2EwSDVaY19VQ1FCRTRCR0FwUjc5S2ZpTnlaUGRIS2owcURka1BSTF9UYnU0bWpMLW9mZmZGRE50R1JDYklUQUZIUGFmX0hkbEJsRGFnVVhuWnBONHlUODVnT0N1d0ZxaUZKNWhCd0xHOFB0Znp6WXdRLVdn',
         id: 11,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1757591219.451601,
         hostOnly: false,
         httpOnly: false,
         name: 'PREF',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'f6=40000000&tz=Asia.Bangkok&f7=100',
         id: 12,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012542,
         hostOnly: false,
         httpOnly: false,
         name: 'SAPISID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: '_vg-Kw7af5LTBJq0/A7jsRVrzAZ2r9KIea',
         id: 13,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012656,
         hostOnly: false,
         httpOnly: false,
         name: 'SID',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'g.a000mQgFegrpHiQI5ErTzgDMnU-BwcjKhaxRNqZEMCerMga7uTFIiRP2up6cLRjSCLgue5QO2wACgYKARcSARMSFQHGX2Mirg-qzyZamOM1mKUOTb7WpBoVAUF8yKqKF34BvJnyxbII2XvAOI5b0076',
         id: 14,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1754567223.567714,
         hostOnly: false,
         httpOnly: false,
         name: 'SIDCC',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'AKEyXzXbVIWZjZD1Kx8VwVem-naxdXWyC75zQ-fh3PUvkLJK2Kyl3iTKEY5CN_-fEx-a88Bd0A',
         id: 15,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1756798150.012496,
         hostOnly: false,
         httpOnly: true,
         name: 'SSID',
         path: '/',
         sameSite: 'unspecified',
         secure: true,
         session: false,
         storeId: '0',
         value: 'AdTFnWRTa-V51R4r-',
         id: 16,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1723031228,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-3opvp5',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhAJJCEiUFD50BzWt0jLTakv4Jg0jVFNOheBbjgxeLT71IAiBqdYPWB8blSoq5R_yZj3R0P3arQUbO1UHtCpRmEkuJtw%3AQUQ3MjNmekd5UFU4VzQ2ejV4Wi1JRDE4Z0VoSVB5Mm52WGhaVmJFeDhfYllHS2EwSDVaY19VQ1FCRTRCR0FwUjc5S2ZpTnlaUGRIS2owcURka1BSTF9UYnU0bWpMLW9mZmZGRE50R1JDYklUQUZIUGFmX0hkbEJsRGFnVVhuWnBONHlUODVnT0N1d0ZxaUZKNWhCd0xHOFB0Znp6WXdRLVdn',
         id: 17,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1723031224,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-tladcw',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhAJJCEiUFD50BzWt0jLTakv4Jg0jVFNOheBbjgxeLT71IAiBqdYPWB8blSoq5R_yZj3R0P3arQUbO1UHtCpRmEkuJtw%3AQUQ3MjNmekd5UFU4VzQ2ejV4Wi1JRDE4Z0VoSVB5Mm52WGhaVmJFeDhfYllHS2EwSDVaY19VQ1FCRTRCR0FwUjc5S2ZpTnlaUGRIS2owcURka1BSTF9UYnU0bWpMLW9mZmZGRE50R1JDYklUQUZIUGFmX0hkbEJsRGFnVVhuWnBONHlUODVnT0N1d0ZxaUZKNWhCd0xHOFB0Znp6WXdRLVdn',
         id: 18,
      },
      {
         domain: '.youtube.com',
         expirationDate: 1723031225,
         hostOnly: false,
         httpOnly: false,
         name: 'ST-xuwub9',
         path: '/',
         sameSite: 'unspecified',
         secure: false,
         session: false,
         storeId: '0',
         value: 'session_logininfo=AFmmF2swRQIhAJJCEiUFD50BzWt0jLTakv4Jg0jVFNOheBbjgxeLT71IAiBqdYPWB8blSoq5R_yZj3R0P3arQUbO1UHtCpRmEkuJtw%3AQUQ3MjNmekd5UFU4VzQ2ejV4Wi1JRDE4Z0VoSVB5Mm52WGhaVmJFeDhfYllHS2EwSDVaY19VQ1FCRTRCR0FwUjc5S2ZpTnlaUGRIS2owcURka1BSTF9UYnU0bWpMLW9mZmZGRE50R1JDYklUQUZIUGFmX0hkbEJsRGFnVVhuWnBONHlUODVnT0N1d0ZxaUZKNWhCd0xHOFB0Znp6WXdRLVdn',
         id: 19,
      },
   ],
}
